package com.example.flashfeed.models

// Import necessary Room and Serializable libraries
import androidx.room.Entity
import androidx.room.PrimaryKey
import java.io.Serializable

// Marks this class as a Room database entity with the table name "articles"
@Entity(tableName = "articles")
data class Article(
    // Primary key for the table, auto-generated by Room
    @PrimaryKey(autoGenerate = true)
    var id: Int? = null,

    val author: String,        // Name of the article's author
    val content: String,       // Full content of the article
    val description: String,   // Short description of the article
    val publishedAt: String,   // Date and time of publication
    val source: Source,        // The source of the article (Custom data type Source)
    val title: String,         // Title of the article
    val url: String,           // Link to the full article
    val urlToImage: String     // URL of the article's image
) : Serializable // Implements Serializable to allow passing the object between activities/fragments
